server:
  port: 80

spring:
  #加上这个，保证修改了代码，应用不重启得同时加载类，节约时间
  devtools:
    restart:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

feign:
  hystrix:
    enabled: true